#!/bin/bash

docker network create pet-clinic 2> /dev/null;

docker run \
	-d \
	--rm \
	--name mysql \
	--network pet-clinic \
	-p 3306:3306 \
	-v /home/nagrarok/dev/docker-mysql-databases/5.7.35:/var/lib/mysql/ \
	-e MYSQL_ROOT_PASSWORD="{SQL}#42sqlpass" \
	mysql:5.7.35

#docker run -d --rm --name mysql --network pet-clinic -p 3306:3306 -v /home/nagrarok/dev/docker-mysql-databases/5.7.35:/var/lib/mysql/ -e MYSQL_ROOT_PASSWORD="{SQL}#42sqlpass" mysql:5.7.35

docker build \
	-t springio/gs-spring-boot-docker \
	--build-arg TARGET='spring-petclinic/target/spring-petclinic-2.5.0-SNAPSHOT.jar' \
	--tag pet-clinic .

docker run \
	-d \
	--rm \
	-p 8080:8080 \
	--name pet-clinic \
	--network pet-clinic \
	pet-clinic